# server:
#   port: 8082
#   servlet:
#     context-path: /

# spring:
#   application:
#     name: portal_pampacare
#   jpa:
#     show-sql: false
#     hibernate:
#       ddl-auto: update
#     properties:
#       hibernate:
#       dialect: org.hibernate.dialect.MySQL8Dialect
#   jmx:
#     enabled: false
#   datasource:
#     url: jdbc:postgresql://localhost:5432/portal_pampacare?useTimezone=true&serverTimezone=UTC
#     username: postgres
#     password: postgres

# eureka:
#   instance:
#     hostname: localhost
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka/eureka